apiVersion: apps/v1
kind: Deployment
metadata:
  name: module13-go-prometheus-app
spec:
  selector:
    matchLabels:
      app: module13-go-prometheus-app
  template:
    metadata:
      labels:
        app: module13-go-prometheus-app
    spec:
      containers:
        - name: module13-go-prometheus-app
          image: docker.io/lyzhang1999/module13-go-prometheus-app:latest
          ports:
            - containerPort: 8080
              name: web
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: curl
          image: docker.io/curlimages/curl
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true;
              do
                curl http://127.0.0.1:8080/api/cart
                sleep 2
                curl http://127.0.0.1:8080/api/pay
                sleep 2
              done
---
apiVersion: v1
kind: Service
metadata:
  name: module13-go-prometheus-app
  labels:
    app: module13-go-prometheus-app
spec:
  selector:
    app: module13-go-prometheus-app
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30901
  type: NodePort
