apiVersion: autoscaling.aiops.com/v1
kind: CronHPA
metadata:
  name: cronhpa-sample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  jobs:
    - name: "scale-up"
      schedule: "*/1 * * * *"  # Every minute
      targetSize: 3