# This rule is not used by the project cronhpa itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over autoscaling.aiops.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronhpa
    app.kubernetes.io/managed-by: kustomize
  name: cronhpa-admin-role
rules:
- apiGroups:
  - autoscaling.aiops.com
  resources:
  - cronhpas
  verbs:
  - '*'
- apiGroups:
  - autoscaling.aiops.com
  resources:
  - cronhpas/status
  verbs:
  - get
